# Generated by Django 5.0.4 on 2024-04-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('gr', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidad')], default='Kg', max_length=10),
        ),
    ]
