# Generated by Django 5.0.4 on 2024-04-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv_app', '0002_item_price_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Carnes', 'Carnes'), ('Huevos', 'Huevos'), ('Cereales', 'Cereales'), ('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Dulces', 'Dulces'), ('Bebidas', 'Bebidas')], default='Lacteos', max_length=10),
        ),
    ]
