# Generated by Django 5.0.4 on 2024-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv_app', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('gr', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidad')], default='kg', max_length=10),
        ),
    ]
