# Generated by Django 5.0.4 on 2024-04-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inv_app', '0005_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
